import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("http://localhost:8000/login")
    page.get_by_role("link", name="Sign up").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").press("CapsLock")
    page.get_by_role("textbox", name="Username").fill("W")
    page.get_by_role("textbox", name="Username").press("CapsLock")
    page.get_by_role("textbox", name="Username").fill("Whitney")
    page.get_by_role("textbox", name="Password", exact=True).click()
    page.get_by_role("textbox", name="Password", exact=True).press("CapsLock")
    page.get_by_role("textbox", name="Password", exact=True).fill("P")
    page.get_by_role("textbox", name="Password", exact=True).press("CapsLock")
    page.get_by_role("textbox", name="Password", exact=True).fill("Password1")
    page.get_by_role("textbox", name="Confirm Password").click()
    page.get_by_role("textbox", name="Confirm Password").press("CapsLock")
    page.get_by_role("textbox", name="Confirm Password").fill("P")
    page.get_by_role("textbox", name="Confirm Password").press("CapsLock")
    page.get_by_role("textbox", name="Confirm Password").fill("Password2")
    page.get_by_role("link", name="Sign in").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("admin")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("admin123")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("link", name="📊 Analytics").click()
    page.get_by_role("link", name="Live Map").click()
    page.get_by_role("button", name="🔔").click()
    page.get_by_role("button", name="🔔").click()
    page.get_by_role("button", name="🛰 Satellite View").click()
    page.get_by_role("link", name="Sign Out").click()
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").fill("admin")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("admin123")
    page.get_by_role("button", name="Sign In").click()
