"""
detection/camera_catalogue.py

GENERATED FILE — do not edit by hand.
Regenerate with:  python tools/fetch_cameras.py

Source : https://www.myt.mu/sinformer/trafficwatch/
Fetched: 2026-08-06 19:14 UTC
Cameras: 38 across 8 regions (9 with verified coordinates)

coords_precision is 'exact' for positions checked against
tools/validate_camera_coords.py (a real OSM road within 40m) and
'unverified' for cameras placed at their region centroid because MYT
publishes no coordinates and nobody has verified this one yet. The UI
aggregates unverified cameras into one per-region marker rather than
plotting individual positions nobody has confirmed.
"""

from __future__ import annotations

SOURCE_PAGE = 'https://www.myt.mu/sinformer/trafficwatch/'
FETCHED_AT = '2026-08-06 19:14 UTC'

CAMERAS: list[dict] = [
    # ── Port Louis Center ───────────────────────────────────────
    {
        "camera_id":        'caudan_north',
        "name":             'Caudan North',
        "region":           'Port Louis Center',
        "lat":              -20.1626,
        "lng":              57.4939,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/rh/prod/CAUDAN_NORTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'caudan_south',
        "name":             'Caudan South',
        "region":           'Port Louis Center',
        "lat":              -20.164,
        "lng":              57.4945,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/CAUDAN_SOUTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'la_chaussee',
        "name":             'La Chaussee Street',
        "region":           'Port Louis Center',
        "lat":              -20.1640344,
        "lng":              57.5003395,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/LA_CHAUSSEE_STREET.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'place_darmes',
        "name":             "Place d'Armes",
        "region":           'Port Louis Center',
        "lat":              -20.1619577,
        "lng":              57.5021109,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/PLACE_DARMES.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'casernes_city_centre',
        "name":             'Casernes City Centre',
        "region":           'Port Louis Center',
        "lat":              -20.1619,
        "lng":              57.4989,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/CASERNES_CITY_CENTRE.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'casernes',
        "name":             'Casernes Brabant Street',
        "region":           'Port Louis Center',
        "lat":              -20.1654977,
        "lng":              57.4921943,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/CASERNES_BRABANT_STREET.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'deschartes_junction',
        "name":             'Deschartes Junction',
        "region":           'Port Louis Center',
        "lat":              -20.1619,
        "lng":              57.4989,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/DESCHARTES_JUNCTION.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'cdm_govt_str_junction',
        "name":             'CDM Govt Str Junction',
        "region":           'Port Louis Center',
        "lat":              -20.1619,
        "lng":              57.4989,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/CDM_GOVT_STR_JUNCTION.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Port Louis South ────────────────────────────────────────
    {
        "camera_id":        'plaine_lauzun_north',
        "name":             'Plaine Lauzun North',
        "region":           'Port Louis South',
        "lat":              -20.188,
        "lng":              57.4905,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/PLAINE_LAUZUN_NORTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'plaine_lauzun_south',
        "name":             'Plaine Lauzun South',
        "region":           'Port Louis South',
        "lat":              -20.188,
        "lng":              57.4905,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/PLAINE_LAUZUN_SOUTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'pailles_motorway',
        "name":             'Pailles Motorway',
        "region":           'Port Louis South',
        "lat":              -20.196876,
        "lng":              57.483271,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/PAILLES_MOTORWAY.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'old_moka_road',
        "name":             'Old Moka Road',
        "region":           'Port Louis South',
        "lat":              -20.188,
        "lng":              57.4905,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/OLD_MOKA_ROAD.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'orleans_street',
        "name":             'Orleans Street',
        "region":           'Port Louis South',
        "lat":              -20.188,
        "lng":              57.4905,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/ORLEANS_STREET.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'immaculee',
        "name":             'Immaculee',
        "region":           'Port Louis South',
        "lat":              -20.188,
        "lng":              57.4905,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/immaculee.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Port Louis North ────────────────────────────────────────
    {
        "camera_id":        'terre_rouge_motorway',
        "name":             'Terre Rouge Motorway',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/TERRE_ROUGE_MOTORWAY.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'abercrombie',
        "name":             'Abercrombie',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/ABERCROMBIE.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'gard_du_nord',
        "name":             'Gare Du Nord',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/GARD_DU_NORD.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'gard_du_nord_2',
        "name":             'Gare Du Nord 2',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/GARD_DU_NORD_2.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'queen_street_1',
        "name":             'Queen Street 1',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/QUEEN_STREET_1.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'queen_street_2',
        "name":             'Queen Street 2',
        "region":           'Port Louis North',
        "lat":              -20.137,
        "lng":              57.503,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/QUEEN_STREET_2.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Reduit & Ebene ──────────────────────────────────────────
    {
        "camera_id":        'reduit_flyover',
        "name":             'Reduit Flyover',
        "region":           'Reduit & Ebene',
        "lat":              -20.2316888,
        "lng":              57.500093,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/REDUIT_FLYOVER.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'ebene_motorway',
        "name":             'Ebene Motorway',
        "region":           'Reduit & Ebene',
        "lat":              -20.2355,
        "lng":              57.4915,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/EBENE_MOTORWAY.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Beau Bassin & Rose Hill ─────────────────────────────────
    {
        "camera_id":        'beau_bassin_junction',
        "name":             'Beau Bassin Junction',
        "region":           'Beau Bassin & Rose Hill',
        "lat":              -20.233,
        "lng":              57.467,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/BEAU_BASSIN_JUNCTION.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'beau_bassin_main_road',
        "name":             'Beau Bassin Main Road',
        "region":           'Beau Bassin & Rose Hill',
        "lat":              -20.233,
        "lng":              57.467,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/BEAU_BASSIN_MAIN_ROAD.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'plaza',
        "name":             'Plaza',
        "region":           'Beau Bassin & Rose Hill',
        "lat":              -20.233,
        "lng":              57.467,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/PLAZA.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Phoenix & St-Jean ───────────────────────────────────────
    {
        "camera_id":        'dreamton_st_jean',
        "name":             'Dreamton St Jean',
        "region":           'Phoenix & St-Jean',
        "lat":              -20.27,
        "lng":              57.498,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/DREAMTON_ST_JEAN.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'dreamton_phoenix',
        "name":             'Dreamton Phoenix',
        "region":           'Phoenix & St-Jean',
        "lat":              -20.27,
        "lng":              57.498,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/DREAMTON_PHOENIX.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'highlands_motorway',
        "name":             'Highlands Motorway',
        "region":           'Phoenix & St-Jean',
        "lat":              -20.27,
        "lng":              57.498,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/HIGHLANDS_MOTORWAY.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Quatre Bornes & Belle Rose ──────────────────────────────
    {
        "camera_id":        'quatres_bornes',
        "name":             'Quatre Bornes',
        "region":           'Quatre Bornes & Belle Rose',
        "lat":              -20.265,
        "lng":              57.479,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/QUATRES_BORNES.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'belle_rose',
        "name":             'Belle Rose',
        "region":           'Quatre Bornes & Belle Rose',
        "lat":              -20.265,
        "lng":              57.479,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/BELLE_ROSE.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'la_louise',
        "name":             'La Louise',
        "region":           'Quatre Bornes & Belle Rose',
        "lat":              -20.265,
        "lng":              57.479,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/LA_LOUISE.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'palma_road',
        "name":             'Palma Road',
        "region":           'Quatre Bornes & Belle Rose',
        "lat":              -20.265,
        "lng":              57.479,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/PALMA_ROAD.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    # ── Curepipe ────────────────────────────────────────────────
    {
        "camera_id":        'curepipe_metro_1',
        "name":             'Curepipe Metro 1',
        "region":           'Curepipe',
        "lat":              -20.315,
        "lng":              57.525,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/CUREPIPE_METRO_1.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'curepipe_metro_2',
        "name":             'Curepipe Metro 2',
        "region":           'Curepipe',
        "lat":              -20.315,
        "lng":              57.525,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/CUREPIPE_METRO_2.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'jan_palach_south',
        "name":             'Jan Palach South',
        "region":           'Curepipe',
        "lat":              -20.3178309,
        "lng":              57.5272002,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/JAN_PALACH_SOUTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'jan_palach_north',
        "name":             'Jan Palach North',
        "region":           'Curepipe',
        "lat":              -20.3162102,
        "lng":              57.5261022,
        "coords_precision": 'exact',
        "source":           'https://stream.myt.mu/prod/JAN_PALACH_NORTH.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'floreal_road',
        "name":             'Floreal Road',
        "region":           'Curepipe',
        "lat":              -20.315,
        "lng":              57.525,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/FLOREAL_ROAD.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
    {
        "camera_id":        'curepipe_suisse_junction',
        "name":             'Curepipe Suisse Junction',
        "region":           'Curepipe',
        "lat":              -20.315,
        "lng":              57.525,
        "coords_precision": 'unverified',
        "source":           'https://stream.myt.mu/prod/CUREPIPE_SUISSE_JUNCTION.stream_720p/playlist.m3u8',
        "origin":           "myt.trafficwatch",
    },
]

CAMERAS_BY_ID: dict[str, dict] = {c['camera_id']: c for c in CAMERAS}

REGIONS: list[str] = ['Beau Bassin & Rose Hill', 'Curepipe', 'Phoenix & St-Jean', 'Port Louis Center', 'Port Louis North', 'Port Louis South', 'Quatre Bornes & Belle Rose', 'Reduit & Ebene']


def get(camera_id: str) -> dict | None:
    """Catalogue entry for a camera, or None if unknown."""
    return CAMERAS_BY_ID.get(camera_id)
